### ISSUE TITLE
Implementação Livraria para vaga pleno II

### ISSUE THREAD

**Issue by thaislaure** [douglas-tsc/ewave-mt-processo-seletivo#1]
Segue abaixo link do projeto:
https://github.com/thaislaure/ewave-Livraria-PlenoII

**Comment by rodolfocop** [comment]
Olá @thaislaure , iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Olá @thaislaure , repassamos ao Wender nossa avaliação. Assim que possível ele entrará em contato com você. Até mais.

**Comment by thaislaure** [comment]
Olá @rodolfocop, ok fico no aguardo.
Até mais.
