### ISSUE TITLE
Implementação Favor de Livreria para vaga de Pleno II

### ISSUE THREAD

**Issue by marcelovargas** [douglas-tsc/ewave-mt-processo-seletivo#11]
Segue abaixo o link do projeto:
https://github.com/marcelovargas/ewave-livraria-pleno-II.git

**Comment by rodolfocop** [comment]
Olá @marcelovargas ,  iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
