### ISSUE TITLE
[ewave-favo-de-mel-senior] - Processo Seletivo Dev Senior

### ISSUE THREAD

**Issue by DiogoSBorges** [douglas-tsc/ewave-mt-processo-seletivo#13]
Segue o link abaixo:

[ewave-favo-de-mel-senior](https://github.com/DiogoSBorges/ewave-favo-de-mel-senior)

**Comment by rodolfocop** [comment]
Foi encaminhado ao Wender as considerações, assim que possível ele informara o resultado.
