### ISSUE TITLE
ewave-favo-de-mel-plenoII

### ISSUE THREAD

**Issue by IgorJordany** [douglas-tsc/ewave-mt-processo-seletivo#15]
Segue o link abaixo:

[ewave-favo-de-mel-plenoII](https://github.com/IgorJordany/ewave-favo-de-mel-plenoII.git)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
