### ISSUE TITLE
ewave-livraria-Pleno II

### ISSUE THREAD

**Issue by claudineidesenvolvedor** [douglas-tsc/ewave-mt-processo-seletivo#16]
https://github.com/claudineidesenvolvedor/livrarias

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.

**Comment by claudineidesenvolvedor** [comment]
Grato.
