### ISSUE TITLE
ewave-favodemel-plenoII

### ISSUE THREAD

**Issue by brunohdf97** [douglas-tsc/ewave-mt-processo-seletivo#17]
https://github.com/brunocanmaster/ewave-favodemel-plenoII/tree/master

Segue projeto...

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Após a desistência do mesmo estamos fechando esse envio.
