### ISSUE TITLE
Implementação Livraria para vaga pleno II

### ISSUE THREAD

**Issue by WesleyTapajoz** [douglas-tsc/ewave-mt-processo-seletivo#18]
Segue link do projeto.
https://github.com/WesleyTapajoz/livraria.git

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
