### ISSUE TITLE
Ewave-Eventos-PlenoII

### ISSUE THREAD

**Issue by CleytonGoncalves** [douglas-tsc/ewave-mt-processo-seletivo#19]
Segue abaixo link do projeto:
https://github.com/CleytonGoncalves/ewave-eventos-plenoii

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
