### ISSUE TITLE
Implementação Livraria para vaga de Pleno II

### ISSUE THREAD

**Issue by brunodmilani** [douglas-tsc/ewave-mt-processo-seletivo#2]
https://github.com/brunodmilani/ewave-livraria-pleno-II

**Comment by rodolfocop** [comment]
Olá @brunodmilani , iremos verificar e assim que finalizamos informaremos a você.

**Comment by brunodmilani** [comment]
Olá @rodolfocop, fico no aguardo.

**Comment by rodolfocop** [comment]
Olá @brunodmilani , repassamos ao Wender nossa avaliação. 
Assim que possível ele entrará em contato com você. 
Até mais.
