### ISSUE TITLE
Implementação Ewave Livraria para vaga de Pleno II

### ISSUE THREAD

**Issue by gideaosouza** [douglas-tsc/ewave-mt-processo-seletivo#20]
Segue abaixo o link do projeto
[ewave-livraria-plenoII](https://github.com/gideaosouza/ewave-livraria-plenoII)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
