### ISSUE TITLE
Implementação Livraria ToDo para a vaga de Pleno II

### ISSUE THREAD

**Issue by henriquehrf** [douglas-tsc/ewave-mt-processo-seletivo#22]
Segue abaixo o link do projeto.

<a href="https://github.com/henriquehrf/Ewave-Livraria-PlenoII">Ewave-Livraria-PlenoII</a>

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
