### ISSUE TITLE
Solução para o tema: Favo de mel

### ISSUE THREAD

**Issue by gfmcoding** [douglas-tsc/ewave-mt-processo-seletivo#23]
[ewave-favo-de-mel-pleno-um](https://github.com/gfmcoding/ewave-favo-de-mel-pleno-um)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Após o declino do mesmo pela vaga, estou fechando a entrega.
