### ISSUE TITLE
ewave-livraria-pleno-II

### ISSUE THREAD

**Issue by rodrigomguerreiro** [douglas-tsc/ewave-mt-processo-seletivo#24]
https://github.com/rodrigomguerreiro/ewave-livraria-pleno-II

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
