### ISSUE TITLE
Implementação Eventos para vaga de Sênior

### ISSUE THREAD

**Issue by fps182** [douglas-tsc/ewave-mt-processo-seletivo#25]
Segue abaixo o link do projeto

[ewave-eventos-senior](https://github.com/fps182/ewave-eventos-senior)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Gestor nossas avaliações.
Assim que possível ele entrará em contato com você.
