### ISSUE TITLE
Implementação Favo de mel para a vaga de Sênior

### ISSUE THREAD

**Issue by brunoravanhani** [douglas-tsc/ewave-mt-processo-seletivo#26]
[ewave-favodemel-senior](https://github.com/brunoravanhani/ewave-favodemel-senior)

**Comment by brunoravanhani** [comment]
Finalizado.

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
