### ISSUE TITLE
Implementação Livraria para vaga de Pleno

### ISSUE THREAD

**Issue by DeivisonMaster** [douglas-tsc/ewave-mt-processo-seletivo#27]
https://github.com/DeivisonMaster/ewave-livraria-pleno

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by DeivisonMaster** [comment]
Olá, tudo bem? não esta finalizado ainda, e estou no prazo

**Comment by rodolfocop** [comment]
Sem problemas, nos informe após a finalização. 
Abraços e boa sorte!

**Comment by rodolfocop** [comment]
Repassamos ao Gestor nossas avaliações.
Assim que possível ele entrará em contato com você.
