### ISSUE TITLE
Implementação Livraria para vaga de Senior

### ISSUE THREAD

**Issue by brunoravanhani** [douglas-tsc/ewave-mt-processo-seletivo#29]
[ewave-livraria-senior](https://github.com/brunoravanhani/ewave-livraria-senior)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
