### ISSUE TITLE
ewave-livraria-pleno-ii

### ISSUE THREAD

**Issue by aarondmt** [douglas-tsc/ewave-mt-processo-seletivo#3]
https://github.com/aarondmt/ewave-livraria-pleno-ii

**Comment by rodolfocop** [comment]
Olá @aarondmt , iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Olá @aarondmt  , repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
