### ISSUE TITLE
Implementação ToDo para vaga de Sênior

### ISSUE THREAD

**Issue by pablomgg** [douglas-tsc/ewave-mt-processo-seletivo#30]
Segue abaixo o link do projeto.

[ewave-todo-senior](https://github.com/pablomorigi/ewave-livraria-senior)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
