### ISSUE TITLE
Implementação Livraria - Pleno II

### ISSUE THREAD

**Issue by juliinvaz** [douglas-tsc/ewave-mt-processo-seletivo#31]
Segue abaixo o link do projeto.

[ewave-livraria-pleno2](https://github.com/juliinvaz/ewave-livraria-pleno2)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
