### ISSUE TITLE
Livraria Pleno ii - Alexandre Moshage

### ISSUE THREAD

**Issue by alexandremoshage** [douglas-tsc/ewave-mt-processo-seletivo#32]
https://github.com/alexandremoshage/livraria

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by alexandremoshage** [comment]
Olá, fico no aguardo, obrigado!

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
