### ISSUE TITLE
Implementação Favo de mel para vaga de Arquiteto

### ISSUE THREAD

**Issue by fernandovictorTI** [douglas-tsc/ewave-mt-processo-seletivo#34]
Segue link do projeto.
https://github.com/fernandovictorTI/processo-seletivo-ewave-arquiteto-fev-2021

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
