### ISSUE TITLE
Implementação Livraria ToDo para a vaga de Senior

### ISSUE THREAD

**Issue by henriquehrf** [douglas-tsc/ewave-mt-processo-seletivo#35]
Segue abaixo o link do projeto.

[Ewave-Livraria-Senior](https://github.com/henriquehrf/Ewave-Livraria-Senior)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
