### ISSUE TITLE
Desafio - Implementação livaria To - Do

### ISSUE THREAD

**Issue by cleverson85** [douglas-tsc/ewave-mt-processo-seletivo#36]
Ficou faltando o desenvolvimento dos itens abaixo.
-Informar ao Administrador do Sistema caso um livro extrapole o prazo máximo de dias emprestado.
-O Usuário que infringir a regra dos dias fica impossibilitado de emprestar qualquer outro livro até a devolução e só poderá -emprestar novamente após 30 dias.
-Livros emprestados deverão estar indisponiveis para outros Usuários.
-Permitir reservar livros.

https://github.com/cleverson85/todo-bookstore-api
https://github.com/cleverson85/todo-bookstore-frontend

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
