### ISSUE TITLE
Implementação favo de Mel para vaga de Sênior

### ISSUE THREAD

**Issue by dgoangelo** [douglas-tsc/ewave-mt-processo-seletivo#37]
[Ewave-FavoDeMel-Senior](https://github.com/dgoangelo/Ewave-FavoDeMel-Senior)

**Comment by rodolfocop** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
