### ISSUE TITLE
Implementação Favo de mel para vaga de Pleno 2

### ISSUE THREAD

**Issue by ederbraga** [douglas-tsc/ewave-mt-processo-seletivo#4]
Segue o link do projeto.

[ewave-favodemel-pleno2](https://github.com/ederbraga/ewave-favodemel-pleno2.git)

**Comment by rodolfocop** [comment]
Olá @ederbraga , iremos verificar e assim que finalizamos informaremos a você.

**Comment by ederbraga** [comment]
tudo bem!

**Comment by rodolfocop** [comment]
Olá @ederbraga , repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
