### ISSUE TITLE
Implementação do projeto Livraria para a vaga de Pleno II

### ISSUE THREAD

**Issue by vinibaum** [douglas-tsc/ewave-mt-processo-seletivo#42]
Segue abaixo link do projeto:

[ewave-livraria-plenoII](https://github.com/vinibaum/ewave-livraria-plenoII)

**Comment by fernandovictorTI** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.

**Comment by vinibaum** [comment]
Ok, obrigado!
