### ISSUE TITLE
ewave-livraria-plenoII

### ISSUE THREAD

**Issue by jpaulomc** [douglas-tsc/ewave-mt-processo-seletivo#43]
Segue o link do projeto: [ewave-livraria-plenoII](https://github.com/jpaulomc/ewave-livraria-plenoII)

**Comment by fernandovictorTI** [comment]
Olá, iremos verificar e assim que finalizamos informaremos a você.

**Comment by jpaulomc** [comment]
Ok.

**Comment by fernandovictorTI** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.

**Comment by jpaulomc** [comment]
Ok, Obrigado Fernando!
