### ISSUE TITLE
Implementação Favo de mel para vaga de Arquiteto

### ISSUE THREAD

**Issue by CleydersonPereira** [douglas-tsc/ewave-mt-processo-seletivo#46]
Segue abaixo o link do projeto

[ewave-favo-de-mel-arquitetura](https://github.com/CleydersonPereira/ewave-favo-de-mel-arquitetura)

**Comment by fernandovictorTI** [comment]
Repassamos ao Wender nossas avaliações.
Assim que possível ele entrará em contato com você.
