### ISSUE TITLE
Implementação Livraria para vaga de Arquiteto Java

### ISSUE THREAD

**Issue by orlandoburli** [douglas-tsc/ewave-mt-processo-seletivo#5]
Segue link do projeto.

https://github.com/orlandoburli/ewave-livraria-arquiteto-java

**Comment by rodolfocop** [comment]
Olá @orlandoburli , iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
@orlandoburli , repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
