### ISSUE TITLE
ewave - Livraria - Pleno II ou Pleno I

### ISSUE THREAD

**Issue by alexandremoshage** [douglas-tsc/ewave-mt-processo-seletivo#6]
Boa noite, segue meu projeto
https://github.com/alexandremoshage/livraria-ewave

**Comment by rodolfocop** [comment]
Olá @alexandremoshage reabri sua issue para que possamos avaliar, assim que verificarmos informaremos a você.

**Comment by rodolfocop** [comment]
@alexandremoshage , repassamos ao Wender nossa avaliação.
Até mais.
