### ISSUE TITLE
ewave - Livraria - Pleno II ou Pleno I

### ISSUE THREAD

**Issue by diegolobo** [douglas-tsc/ewave-mt-processo-seletivo#7]
[ewave-livraria-pleno](https://github.com/diegolobo/ewave-livraria-pleno)

**Comment by rodolfocop** [comment]
Olá @diegolobo ,  iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Olá @diegolobo , repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
