### ISSUE TITLE
Implementação Gerenciamento de eventos vaga Senior

### ISSUE THREAD

**Issue by marcosfaneli** [douglas-tsc/ewave-mt-processo-seletivo#8]
Segue link abaixo

https://github.com/marcosfaneli/ewave-eventos-Senior

**Comment by rodolfocop** [comment]
Iremos verificar e assim que finalizamos informaremos a você.

**Comment by rodolfocop** [comment]
Repassamos ao Wender nossa avaliação.
Assim que possível ele entrará em contato com você.
Até mais.
